# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rVb7h6zUuMbEcuV-gI6L5kXQdlsGbBnv

**Importing Important Libraries**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
# %matplotlib inline
from matplotlib import style
style.use('dark_background')

"""Now, loading dataset given in task pdf into notebook

"""

iris_df =pd.read_csv('/content/Iris.csv')
print("The dataset is fetched successfully")

iris_df

"""**Data Exploration**"""

#check shape of data
iris_df.shape

#check basic information of data
iris_df.info()

#check statistical summary of data
iris_df.describe()

#check null values
iris_df.isnull().sum()

print("unique number of values in dataset species:",iris_df["Species"].nunique())
print("Unique Species in iris dataset:",iris_df["Species"].unique())

"""*   There are 3 species in iris dataset that is       **'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'.**

**Exploratorty Data Analysis**

***Data Visualization***
"""

sns.pairplot(iris_df, hue = "Species",markers = "x")
plt.show()

"""

*   It shows that Iris-Setosa is seperated from both other species in all features..
"""

plt.figure(figsize=(15,5))
plt.subplot(1,2,1)
sns.scatterplot(x='SepalLengthCm',y='PetalLengthCm',data=iris_df,hue='Species')

plt.subplot(1,2,2)
sns.scatterplot(x='SepalWidthCm',y='PetalWidthCm',data=iris_df,hue='Species')

plt.show()

#Check correlation in Dataset
iris_df.corr()

#Use Heatmap to see correlation
plt.figure(figsize=(10,7))
sns.heatmap(iris_df.corr(),annot = True,cmap = "Oranges_r")
plt.show()

"""

*   In the above heatmap we can see petal length and petal width is highly correlated.
"""

#Check value counts
iris_df["Species"].value_counts().plot(kind="pie",autopct = "%1.1f%%",shadow=True, figsize=(5,5))
plt.title("Percentage values in each Species", fontsize = 12 , c = "g")
plt.ylabel("",fontsize=10,c="r")
plt.show()

"""

*   We can see all the  species has equal values in dataset
*   Iris-Setosa:50
*   Iris-Versicolor:50
*   Iris-Virginica:50



"""

sns.jointplot(data = iris_df , x = "SepalLengthCm", y = "SepalWidthCm" , size = 7 , hue = "Species")

plt.show()

sns.jointplot(data = iris_df , x = "PetalLengthCm", y = "PetalWidthCm" , size = 7 , hue = "Species")

plt.show()